### PR TITLE
ES12 SEM

### PR DESCRIPTION
**Pull request by dvn-lazywinner**
ES12 Supported code for Syntax Editor Macros

### CODE REVIEW

**Comment by dvn-lazywinner** [comment]
First commit for ES12 Scripts in SEM

**Comment by wiz0floyd** [comment]
Hi there! Thank you for your contribution. Please review the readme and contributing files for this repository. This is not meant to be a ServiceNow app that you install on your instance. It's a collection of useful syntax macros that you can manually add to your instance. Please change your PR to create a script within the folder structure.

**Comment by dvn-lazywinner** [comment]
But it says to import the app in servicenow instance under contributing.md.
While importing it says "No Application file exists".

Shall I create a folder and just add scripts and merge to main?

**Comment by wiz0floyd** [comment]
Yes please. It looks like there was a copy paste error in the contributing file. I've fixed it.

**Pull request closed without merging**
