### PR TITLE
created syntax editor macro for parfilters in UIB

### PR DESCRIPTION
**Pull request by TRIGGEREDcoder**
Once the user enters applyFilter in the editor, the macro populates on the editor which devs can modify or use at is while configuring UIB UX client scripts

### CODE REVIEW

**Comment by TRIGGEREDcoder** [comment]
Hi Shakeel, can you give more details on why it was closed ? comments would be beneficial.

**Comment by am-shakeel** [comment]
Original content - https://developer.servicenow.com/dev.do#!/reference/next-experience/vancouver/now-components/sn-component-filter/uib-setup#connect-the-filter-to-a-data-visualization-component

**Comment by TRIGGEREDcoder** [comment]
Ya so this is how it works, there is no dynamic content to the filter script. parFilters state parameter is constant, if you use anything else it will not work. rather than writing the whole script, you can use the syntax applyFilter which would give you the code.

**Comment by am-shakeel** [comment]
Screenshot of the Original content - image

**Comment by am-shakeel** [comment]
THis is your submitted script
image

**Comment by TRIGGEREDcoder** [comment]
This is what I am saying, it will not change. this script is static as the stateParameter wont change and the UX Client script include won't change. Anyways.

**Comment by am-shakeel** [comment]
It appears that this contribution is a duplicate or resembles spam, potentially aiming to game the Hacktoberfest event. As a reminder, submissions marked as spam may lead to account restrictions or disqualifications. Please ensure to make unique and meaningful contributions, and refrain from spamming or duplicating submissions. Closing this as spam.

**Pull request closed without merging**
